login:
  facebook_app_id:
    default: ''
    regex: "^\\d+$"
    client: true
plugins:
  guest_locker_enabled:
    default: false
    client: true
  guest_locker_topic_views_threshold:
    default: 1
    client: true
  guest_locker_waiting_seconds:
    default: 10
    client: true
  social_locker_enabled:
    default: false
    client: true
  social_locker_guest_threshold:
    default: 1
    client: true
  social_locker_user_threshold:
    default: 0
    client: true
  social_locker_waiting_seconds:
    default: 10
    client: true
  facebook_page_url:
    default: ''
    client: true
  twitter_handle:
    default: ''
    client: true
